### ISSUE TITLE
static assets

### ISSUE THREAD

**Issue by weyj4** [trailsjs/trailpack-express4#10]
Right now you serve up a static directory by putting the following in app.config.main.paths:
```www: path.resolve(__dirname, '..', 'dist')```

Would it make sense to modify this configuration so that you only need to put:
```www: 'dist'``` ?

Right now trailpack-hapi uses something similar to the 2nd option above, and they need to both work the same. Is there a good reason to keep path.resolve in the main app?

**Comment by jaumard** [comment]
I didn't test with only `dist` I think, because in the default main config `path.resolve` is used https://github.com/trailsjs/trails/blob/master/archetype/config/main.js so I use same :) 
I don't know if only `dist` will work directly with the current code, need some tests depends of what way you choose

**Comment by weyj4** [comment]
OK. It won't work with only ```dist``` now, we'd have to modify the trailpack. It sounds like it might be easiest to leave this as-is and modify trailpack-hapi to use ```path.resolve```. Thanks!
